# Generated by Django 3.1.3 on 2020-11-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=30)),
                ('livestock', models.CharField(choices=[('poultry', 'poultry'), ('cows', 'cows'), ('sheep', 'sheep'), ('goats', 'goats')], max_length=20)),
                ('animal_count', models.IntegerField()),
                ('manager', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('animal_type', models.CharField(choices=[('poultry', 'poultry'), ('cows', 'cows'), ('sheep', 'sheep'), ('goats', 'goats')], max_length=20)),
                ('date_of_birth', models.DateTimeField(blank=True)),
                ('date_inseminated', models.DateTimeField(blank=True)),
                ('check_date', models.DateTimeField(blank=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_app.farm')),
            ],
        ),
    ]
